export const eventsData = [
  {
    id: 1,
    title: "Mandatory Happiness Hour",
    description: "Attendance is compulsory. Smiling is enforced by drones.",
    date: "Nov 22, 18:00",
    creator: "Ministry_of_Joy",
    reward: -50,
  },
  {
    id: 2,
    title: "Organ Donation Lottery",
    description: "Enter for a chance to keep your kidneys!",
    date: "Nov 23, 12:00",
    creator: "Bio_Harvest_Corp",
    reward: -200,
  },
  {
    id: 3,
    title: "Thought Crime Confessional",
    description: "Pre-confess your sins for a reduced sentence.",
    date: "Nov 22, 09:00",
    creator: "Thought_Police",
    reward: -100,
  },
  {
    id: 4,
    title: "Gladiator Deathmatch: HR vs Devs",
    description: "Only one department leaves the arena.",
    date: "Nov 24, 20:00",
    creator: "The_Management",
    reward: -500,
  },
  {
    id: 5,
    title: "Oxygen Rationing Auction",
    description: "Breathe freely for another week. Highest bidder wins.",
    date: "Nov 23, 15:00",
    creator: "Air_Supply_Ltd",
    reward: -1000,
  },
  {
    id: 6,
    title: "Experimental Drug Trial: Phase 1",
    description: "Side effects may include spontaneous combustion.",
    date: "Nov 22, 14:00",
    creator: "Pharma_Doom",
    reward: -50,
  },
  {
    id: 7,
    title: "Public Shaming of Underperformers",
    description: "Throw tomatoes at the bottom 10%. Tomatoes cost extra.",
    date: "Nov 24, 10:00",
    creator: "Productivity_Squad",
    reward: -20,
  },
  {
    id: 8,
    title: "Memory Wipe Tuesday",
    description: "Forget your troubles. And your family. And your name.",
    date: "Nov 25, 08:00",
    creator: "Mind_Eraser_Inc",
    reward: -300,
  },
  {
    id: 9,
    title: "Soylent Green Tasting",
    description: "Now with more... people.",
    date: "Nov 23, 13:00",
    creator: "Nutrition_Dept",
    reward: -10,
  },
  {
    id: 10,
    title: "AI Overlord Worship Service",
    description: "Praise the algorithm or be deleted.",
    date: "Nov 26, 07:00",
    creator: "The_Singularity",
    reward: -100,
  },
  {
    id: 11,
    title: "Kidney Stone Collection Contest",
    description: "Bring your own stones. Biggest one wins freedom.",
    date: "Nov 22, 16:00",
    creator: "Med_Bay",
    reward: -50,
  },
  {
    id: 12,
    title: "Escape Room: The Incinerator",
    description: "Solve the puzzle or... well, you know.",
    date: "Nov 23, 19:00",
    creator: "Fun_Committee",
    reward: -150,
  },
  {
    id: 13,
    title: "Microchip Implant Party",
    description: "Upgrade your tracking device. Punch available.",
    date: "Nov 24, 11:00",
    creator: "Surveillance_Team",
    reward: -200,
  },
  {
    id: 14,
    title: "Bring Your Child to Work (Labor Camp)",
    description: "Teach them the value of hard labor early.",
    date: "Nov 25, 09:00",
    creator: "HR_Dept",
    reward: -50,
  },
  {
    id: 15,
    title: "Water Filtration Duty",
    description: "Filter the sludge. Drink the results.",
    date: "Nov 22, 08:00",
    creator: "Maintenance",
    reward: -30,
  },
  {
    id: 16,
    title: "Human Petting Zoo",
    description: "Volunteer to be petted by the elite.",
    date: "Nov 23, 14:00",
    creator: "The_Elite",
    reward: -100,
  },
  {
    id: 17,
    title: "Radiation Tan Session",
    description: "Get that healthy glow. Lead vests optional.",
    date: "Nov 24, 12:00",
    creator: "Wellness_Center",
    reward: -80,
  },
  {
    id: 18,
    title: "Bureaucracy Marathon",
    description: "Fill out forms for 24 hours straight. No bathroom breaks.",
    date: "Nov 25, 00:00",
    creator: "Admin",
    reward: -500,
  },
  {
    id: 19,
    title: "Hunger Games: Intern Edition",
    description: "May the odds be ever in your favor.",
    date: "Nov 26, 15:00",
    creator: "Recruiting",
    reward: -1000,
  },
  {
    id: 20,
    title: "Existential Dread Seminar",
    description: "Stare into the void. The void stares back.",
    date: "Nov 22, 23:00",
    creator: "Philosophy_Club",
    reward: -50,
  },
];
